# Generated by Django 6.0.3 on 2026-05-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0004_rename_projects_co_project_dd23c6_idx_projects_co_project_3b8aa5_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial — some errors"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=10,
                    ),
                ),
                ("github_repos_found", models.IntegerField(default=0)),
                ("projects_created", models.IntegerField(default=0)),
                ("projects_updated", models.IntegerField(default=0)),
                ("projects_ai_generated", models.IntegerField(default=0)),
                ("drive_files_found", models.IntegerField(default=0)),
                ("certificates_created", models.IntegerField(default=0)),
                ("certificates_skipped", models.IntegerField(default=0)),
                (
                    "errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of error strings encountered during the run",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Plain English summary of what changed this run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.AddField(
            model_name="certificate",
            name="auto_extracted",
            field=models.BooleanField(
                default=False,
                help_text="True if this certificate was extracted by the AI agent, False if manually created",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="drive_file_id",
            field=models.CharField(
                blank=True,
                help_text="Google Drive file ID — used to detect duplicates and avoid re-processing",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="last_agent_run",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last time the agent processed this project",
                null=True,
            ),
        ),
    ]
